### ISSUE TITLE
Not deployed?

### ISSUE THREAD

**Issue by TaylorWoods1** [powston/aemo_nmi_info#2]
% pip3 install aemo-nmi-lookup
ERROR: Could not find a version that satisfies the requirement aemo-nmi-lookup (from versions: none)
ERROR: No matching distribution found for aemo-nmi-lookup

**Comment by iconnor** [comment]
I have not been pushing there but I should, I have been putting the github repo into the requirements file:

aemo_to_tariff @ git+https://github.com/powston/aemo_to_tariff@v0.2.3
aemo_nmi_info @ git+https://github.com/powston/aemo_nmi_info@v0.0.1

but can fix this now
